server:
  port: 8080

spring:
  application:
    name: ${yibot.name}
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${yibot.db.host}:${yibot.db.port}/${yibot.db.db}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${yibot.db.username}
    password: ${yibot.db.password}
    hikari:
      pool-name: ${yibot.name}-jdbc-pool
      connection-timeout: 6000
      minimum-idle: 15
      idle-timeout: 60000
      maximum-pool-size: 200 # should be the same as tomcat max-threads
      transaction-isolation: TRANSACTION_READ_COMMITTED

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath*:mapper/**Mapper.xml
  type-aliases-package: com.yixihan.yibot.db.pojo

  # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


# shiro config
shiro:
  # WebSocket 配置
  ws:
    # 访问密钥，强烈推荐在公网的服务器设置
    access-token: ""
    # 超时回收，默认10秒
    timeout: 10
    # 最大文本消息缓冲区
    max-text-message-buffer-size: 512000
    # 二进制消息的最大长度
    max-binary-message-buffer-size: 512000
    client:
      # 是否启用
      enable: false
    server:
      # 是否启用
      enable: true
      # 反向 Websocket 连接地址，无需该配置字段可删除，将使用默认值 "/ws/shiro"
      url: "/ws"
      # 最大空闲时间，超过这个时间将关闭会话
      max-session-idle-timeout: 900000
  # 线程池配置
  task-pool:
    # 核心线程数（默认线程数）
    core-pool-size: 10
    # 缓冲队列大小
    queue-capacity: 200
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 最大线程数
    max-pool-size: 30
    # 线程池名前缀
    thread-name-prefix: "BotTaskPool-"
  # 插件列表
  plugin-list:
    - com.yixihan.yibot.plugins.OffWorkPlugin
    - com.yixihan.yibot.job.GroupInfoJob
    - com.yixihan.yibot.plugins.StatusPlugins
    - com.yixihan.yibot.plugins.RepeaterPlugins
    - com.yixihan.yibot.plugins.UrlParsePlugin
    - com.yixihan.yibot.plugins.Aria2Plugin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    # health point config
    health:
      enabled: true
      show-details: always

    shutdown:
      enabled: true


# bot config
bot:
  id: ${yibot.bot.id}
  masterId: ${yibot.bot.masterId}

aria2:
  base-url: http://127.0.0.1:20244/open
  upload: "/upload"
  download: "/upload/download/{}"
  list: "/path/page"
  status: "/upload/status"
  health: "/health"